
import java.util.ArrayList;
import java.util.Collections;
import java.util.UUID;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mikkelmoerch
 */
public class Frame extends javax.swing.JFrame {
    static PlayerFactory PF = new PlayerFactory();
    
    /**
     * Creates new form Frame
     */
    public Frame() {
        
        initComponents();
        PF.registerClub("Aab", 1920, getClub1());
        PF.registerClub("AGF", 1889, getClub2());
        PF.registerClub("FCK", 1905, getClub3());
        
        PF.generatePlayers(12);
        
        addToBox(allPlayersBox, PF.getSortedPlayerList(PF.PLAYERS));
        // Add players in club 1 to box of that club
        addToBoxByID(club1Box, PF.getAllClubs().get(0).getPlayers());
        // Add players in club 2 to box of that club
        addToBoxByID(club2Box, PF.getAllClubs().get(1).getPlayers());
        // Add players in club 3 to box of that club
        addToBoxByID(club3Box, PF.getAllClubs().get(2).getPlayers());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allPlayersBox = new javax.swing.JComboBox<Item<Player>>();
        playerAge = new javax.swing.JLabel();
        ageBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        club1Lbl = new javax.swing.JLabel();
        club2Lbl = new javax.swing.JLabel();
        club3Lbl = new javax.swing.JLabel();
        club1Box = new javax.swing.JComboBox<Item<Player>>();
        club2Box = new javax.swing.JComboBox<Item<Player>>();
        club3Box = new javax.swing.JComboBox<Item<Player>>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        /*
        allPlayersBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        */
        allPlayersBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                allPlayersBoxItemStateChanged(evt);
            }
        });

        playerAge.setText("Player's age");

        ageBtn.setText("See age");
        ageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("All players:");

        club1Lbl.setText("Club 1");

        club2Lbl.setText("Club 2");

        club3Lbl.setText("Club 3");

        /*
        club1Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        */
        club1Box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                club1BoxItemStateChanged(evt);
            }
        });

        /*
        club2Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        */
        club2Box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                club2BoxItemStateChanged(evt);
            }
        });

        /*
        club3Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        */
        club3Box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                club3BoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(playerAge)
                .addGap(76, 76, 76)
                .addComponent(ageBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(105, 105, 105)
                        .addComponent(club1Lbl)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(allPlayersBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(club1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(club2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(club3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(club2Lbl)
                        .addGap(138, 138, 138)
                        .addComponent(club3Lbl)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(club1Lbl)
                    .addComponent(club2Lbl)
                    .addComponent(club3Lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allPlayersBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(club1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(club2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(club3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(252, 252, 252)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerAge)
                    .addComponent(ageBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getClub1(){
        return this.club1Lbl;
    }
    
    public JLabel getClub2(){
        return this.club2Lbl;
    }
    
    public JLabel getClub3(){
        return this.club3Lbl;
    }
    
    private void allPlayersBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_allPlayersBoxItemStateChanged

    }//GEN-LAST:event_allPlayersBoxItemStateChanged

    private void ageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageBtnActionPerformed
        Item item = (Item) allPlayersBox.getSelectedItem();
        Player player = (Player) item.getValue();
        int age = player.getAge();
        playerAge.setText(Integer.toString(age));
    }//GEN-LAST:event_ageBtnActionPerformed

    private void club1BoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_club1BoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_club1BoxItemStateChanged

    private void club2BoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_club2BoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_club2BoxItemStateChanged

    private void club3BoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_club3BoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_club3BoxItemStateChanged

    /** Populates a JComboBox with Player Objects in a sorted form.
     * 
     * @param box The ComboBox to be populated
     * @param list The list of Player Objects which will populate the ComboBox
     */
    public void addToBox(JComboBox<Item<Player>> box, ArrayList<Player> list){
        // Clear the ComboBox
        box.removeAllItems();
        // Sort the list
        ArrayList<Player> sortedList = PF.getSortedPlayerList((list));
        // Populate the list
        for(Player player : sortedList){
            box.addItem(new Item<Player>(player, player.getName()));
        }
    }
    
    /** Populates a JComboBox with Player Objects in a sorted form.
     *  Takes a list of UUID objects which will be converted to Player objects
     *  before the box is populated.
     * @param box The ComboBox to be populated.
     * @param list The list of UUID objects which will be converted to Player objects and then populate the given ComboBox.
     */
    public void addToBoxByID(JComboBox<Item<Player>> box, ArrayList<UUID> list){
        // Remove all
        box.removeAllItems();
        // Initiate list to hold Player Objects
        ArrayList<Player> playerList = new ArrayList<Player>();
        // Convert all UUID to Player Objects
        for(UUID player : list){
            playerList.add(PF.getPlayerByID(player));
        }
        // Sort the list
        ArrayList<Player> sortedList = PF.getSortedPlayerList((playerList));
        // Add the sorted list to the box
        for(Player player : sortedList){
            box.addItem(new Item<Player>(player, player.getName()));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*
        PF.register(13, "Kaj",);
        PF.register(14, "Bent",);
        PF.register(12, "Kasper");*/
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ageBtn;
    /*
    private javax.swing.JComboBox<String> allPlayersBox;
    */
    private javax.swing.JComboBox<Item<Player>> allPlayersBox;
    /*
    private javax.swing.JComboBox<String> club1Box;
    */
    private javax.swing.JComboBox<Item<Player>> club1Box;
    private javax.swing.JLabel club1Lbl;
    /*
    private javax.swing.JComboBox<String> club2Box;
    */
    private javax.swing.JComboBox<Item<Player>> club2Box;
    private javax.swing.JLabel club2Lbl;
    /*
    private javax.swing.JComboBox<String> club3Box;
    */
    private javax.swing.JComboBox<Item<Player>> club3Box;
    private javax.swing.JLabel club3Lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel playerAge;
    // End of variables declaration//GEN-END:variables
}
